In [1]:
import pandas as pd
import numpy as np
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

DATA_PATH = "../data/raw"

print("Project started successfully!")

Project started successfully!

In [2]:
print("Files available in raw data folder:")
print(os.listdir(DATA_PATH))

Files available in raw data folder:
['Cleaned_HR_Data_Analysis.csv', 'employee_attrition.csv', 'essential_skills.csv', 'occupation_data.csv', 'software_skills.csv']

In [3]:
attrition_df = pd.read_csv(
    f"{DATA_PATH}/employee_attrition.csv"
)

engagement_df = pd.read_csv(
    f"{DATA_PATH}/Cleaned_HR_Data_Analysis.csv"
)

occupation_df = pd.read_csv(
    f"{DATA_PATH}/occupation_data.csv"
)

essential_skills_df = pd.read_csv(
    f"{DATA_PATH}/essential_skills.csv"
)

software_skills_df = pd.read_csv(
    f"{DATA_PATH}/software_skills.csv"
)

In [4]:
datasets = {
    "Attrition": attrition_df,
    "Engagement": engagement_df,
    "Occupation": occupation_df,
    "Essential Skills": essential_skills_df,
    "Software Skills": software_skills_df
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("=" * 60)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print()

============================================================
Attrition
============================================================
Rows: 1470
Columns: 35

============================================================
Engagement
============================================================
Rows: 2845
Columns: 28

============================================================
Occupation
============================================================
Rows: 1016
Columns: 3

============================================================
Essential Skills
============================================================
Rows: 18200
Columns: 15

============================================================
Software Skills
============================================================
Rows: 31821
Columns: 7

In [5]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    for i, column in enumerate(df.columns, start=1):
        print(f"{i}. {column}")

============================================================
Attrition
============================================================
1. Age
2. Attrition
3. BusinessTravel
4. DailyRate
5. Department
6. DistanceFromHome
7. Education
8. EducationField
9. EmployeeCount
10. EmployeeNumber
11. EnvironmentSatisfaction
12. Gender
13. HourlyRate
14. JobInvolvement
15. JobLevel
16. JobRole
17. JobSatisfaction
18. MaritalStatus
19. MonthlyIncome
20. MonthlyRate
21. NumCompaniesWorked
22. Over18
23. OverTime
24. PercentSalaryHike
25. PerformanceRating
26. RelationshipSatisfaction
27. StandardHours
28. StockOptionLevel
29. TotalWorkingYears
30. TrainingTimesLastYear
31. WorkLifeBalance
32. YearsAtCompany
33. YearsInCurrentRole
34. YearsSinceLastPromotion
35. YearsWithCurrManager

============================================================
Engagement
============================================================
1. Employee ID
2. StartDate
3. Title
4. BusinessUnit
5. EmployeeStatus
6. EmployeeType
7. PayZone
8. EmployeeClassificationType
9. DepartmentType
10. Division
11. DOB
12. State
13. GenderCode
14. RaceDesc
15. MaritalDesc
16. Performance Score
17. Current Employee Rating
18. Survey Date
19. Engagement Score
20. Satisfaction Score
21. Work-Life Balance Score
22. Training Date
23. Training Program Name
24. Training Type
25. Training Outcome
26. Training Duration(Days)
27. Training Cost
28. Age

============================================================
Occupation
============================================================
1. O*NET-SOC Code
2. Title
3. Description

============================================================
Essential Skills
============================================================
1. O*NET-SOC Code
2. Title
3. Element ID
4. Element Name
5. Scale ID
6. Scale Name
7. Data Value
8. N
9. Standard Error
10. Lower CI Bound
11. Upper CI Bound
12. Recommend Suppress
13. Not Relevant
14. Date
15. Domain Source

============================================================
Software Skills
============================================================
1. O*NET-SOC Code
2. Title
3. Workplace Example
4. Element ID
5. Element Name
6. Hot Technology
7. In Demand

In [6]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    display(
        pd.DataFrame({
            "column": df.columns,
            "dtype": df.dtypes.astype(str).values,
            "unique_values": [
                df[col].nunique() for col in df.columns
            ]
        })
    )

============================================================
Attrition
============================================================

                      column  dtype  unique_values
0                        Age  int64             43
1                  Attrition    str              2
2             BusinessTravel    str              3
3                  DailyRate  int64            886
4                 Department    str              3
5           DistanceFromHome  int64             29
6                  Education  int64              5
7             EducationField    str              6
8              EmployeeCount  int64              1
9             EmployeeNumber  int64           1470
10   EnvironmentSatisfaction  int64              4
11                    Gender    str              2
12                HourlyRate  int64             71
13            JobInvolvement  int64              4
14                  JobLevel  int64              5
15                   JobRole    str              9
16           JobSatisfaction  int64              4
17             MaritalStatus    str              3
18             MonthlyIncome  int64           1349
19               MonthlyRate  int64           1427
20        NumCompaniesWorked  int64             10
21                    Over18    str              1
22                  OverTime    str              2
23         PercentSalaryHike  int64             15
24         PerformanceRating  int64              2
25  RelationshipSatisfaction  int64              4
26             StandardHours  int64              1
27          StockOptionLevel  int64              4
28         TotalWorkingYears  int64             40
29     TrainingTimesLastYear  int64              7
30           WorkLifeBalance  int64              4
31            YearsAtCompany  int64             37
32        YearsInCurrentRole  int64             19
33   YearsSinceLastPromotion  int64             16
34      YearsWithCurrManager  int64             18

============================================================
Engagement
============================================================

                        column    dtype  unique_values
0                  Employee ID    int64           2845
1                    StartDate      str           1472
2                        Title      str             32
3                 BusinessUnit      str             10
4               EmployeeStatus      str              2
5                 EmployeeType      str              3
6                      PayZone      str              3
7   EmployeeClassificationType      str              3
8               DepartmentType      str              6
9                     Division      str             25
10                         DOB      str           2664
11                       State      str             28
12                  GenderCode      str              2
13                    RaceDesc      str              5
14                 MaritalDesc      str              4
15           Performance Score      str              4
16     Current Employee Rating    int64              5
17                 Survey Date      str            366
18            Engagement Score    int64              5
19          Satisfaction Score    int64              5
20     Work-Life Balance Score    int64              5
21               Training Date      str            366
22       Training Program Name      str              5
23               Training Type      str              2
24            Training Outcome      str              4
25     Training Duration(Days)    int64              5
26               Training Cost  float64           2813
27                         Age    int64             66

============================================================
Occupation
============================================================

           column dtype  unique_values
0  O*NET-SOC Code   str           1016
1           Title   str           1016
2     Description   str           1016

============================================================
Essential Skills
============================================================

                column    dtype  unique_values
0       O*NET-SOC Code      str            910
1                Title      str            910
2           Element ID      str             10
3         Element Name      str             10
4             Scale ID      str              2
5           Scale Name      str              2
6           Data Value  float64             49
7                    N    int64              1
8       Standard Error  float64             41
9       Lower CI Bound  float64            216
10      Upper CI Bound  float64            234
11  Recommend Suppress      str              2
12        Not Relevant      str              2
13                Date      str             17
14       Domain Source      str              1

============================================================
Software Skills
============================================================

              column dtype  unique_values
0     O*NET-SOC Code   str            923
1              Title   str            923
2  Workplace Example   str           8753
3         Element ID   str            134
4       Element Name   str            134
5     Hot Technology   str              2
6          In Demand   str              2

In [7]:
for name, df in datasets.items():

    missing = (
        df.isnull()
        .sum()
        .sort_values(ascending=False)
    )

    missing = missing[missing > 0]

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    if missing.empty:
        print("No missing values found.")
    else:
        display(missing)

============================================================
Attrition
============================================================
No missing values found.

============================================================
Engagement
============================================================
No missing values found.

============================================================
Occupation
============================================================
No missing values found.

============================================================
Essential Skills
============================================================

Not Relevant    9100
dtype: int64

============================================================
Software Skills
============================================================
No missing values found.

In [8]:
for name, df in datasets.items():

    print(
        f"{name}: {df.duplicated().sum()} duplicate rows"
    )

Attrition: 0 duplicate rows
Engagement: 0 duplicate rows
Occupation: 0 duplicate rows
Essential Skills: 0 duplicate rows
Software Skills: 0 duplicate rows

In [9]:
print("Attrition distribution:")
display(attrition_df["Attrition"].value_counts())

print("\nAttrition percentage:")
display(
    attrition_df["Attrition"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Attrition distribution:

Attrition
No     1233
Yes     237
Name: count, dtype: int64

Attrition percentage:

Attrition
No     83.88
Yes    16.12
Name: proportion, dtype: float64

In [10]:
categorical_columns = attrition_df.select_dtypes(
    include="object"
).columns

for col in categorical_columns:
    print("\n", "=" * 50)
    print(col)
    print("=" * 50)
    print(attrition_df[col].value_counts(dropna=False))

 ==================================================
Attrition
==================================================
Attrition
No     1233
Yes     237
Name: count, dtype: int64

 ==================================================
BusinessTravel
==================================================
BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

 ==================================================
Department
==================================================
Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

 ==================================================
EducationField
==================================================
EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

 ==================================================
Gender
==================================================
Gender
Male      882
Female    588
Name: count, dtype: int64

 ==================================================
JobRole
==================================================
JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

 ==================================================
MaritalStatus
==================================================
MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

 ==================================================
Over18
==================================================
Over18
Y    1470
Name: count, dtype: int64

 ==================================================
OverTime
==================================================
OverTime
No     1054
Yes     416
Name: count, dtype: int64

C:\Users\komal\AppData\Local\Temp\ipykernel_11404\685829880.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = attrition_df.select_dtypes(

In [11]:
numeric_columns = attrition_df.select_dtypes(
    include=np.number
).columns

display(
    attrition_df[numeric_columns].describe().T
)

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,36.923810,9.135373,18.0,30.00,36.0,43.00,60.0
DailyRate,1470.0,802.485714,403.509100,102.0,465.00,802.0,1157.00,1499.0
DistanceFromHome,1470.0,9.192517,8.106864,1.0,2.00,7.0,14.00,29.0
Education,1470.0,2.912925,1.024165,1.0,2.00,3.0,4.00,5.0
EmployeeCount,1470.0,1.000000,0.000000,1.0,1.00,1.0,1.00,1.0
EmployeeNumber,1470.0,1024.865306,602.024335,1.0,491.25,1020.5,1555.75,2068.0
EnvironmentSatisfaction,1470.0,2.721769,1.093082,1.0,2.00,3.0,4.00,4.0
HourlyRate,1470.0,65.891156,20.329428,30.0,48.00,66.0,83.75,100.0
JobInvolvement,1470.0,2.729932,0.711561,1.0,2.00,3.0,3.00,4.0
JobLevel,1470.0,2.063946,1.106940,1.0,1.00,2.0,3.00,5.0
JobSatisfaction,1470.0,2.728571,1.102846,1.0,2.00,3.0,4.00,4.0
MonthlyIncome,1470.0,6502.931293,4707.956783,1009.0,2911.00,4919.0,8379.00,19999.0
MonthlyRate,1470.0,14313.103401,7117.786044,2094.0,8047.00,14235.5,20461.50,26999.0
NumCompaniesWorked,1470.0,2.693197,2.498009,0.0,1.00,2.0,4.00,9.0
PercentSalaryHike,1470.0,15.209524,3.659938,11.0,12.00,14.0,18.00,25.0
PerformanceRating,1470.0,3.153741,0.360824,3.0,3.00,3.0,3.00,4.0
RelationshipSatisfaction,1470.0,2.712245,1.081209,1.0,2.00,3.0,4.00,4.0
StandardHours,1470.0,80.000000,0.000000,80.0,80.00,80.0,80.00,80.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.00,1.0,1.00,3.0
TotalWorkingYears,1470.0,11.279592,7.780782,0.0,6.00,10.0,15.00,40.0
TrainingTimesLastYear,1470.0,2.799320,1.289271,0.0,2.00,3.0,3.00,6.0
WorkLifeBalance,1470.0,2.761224,0.706476,1.0,2.00,3.0,3.00,4.0
YearsAtCompany,1470.0,7.008163,6.126525,0.0,3.00,5.0,9.00,40.0
YearsInCurrentRole,1470.0,4.229252,3.623137,0.0,2.00,3.0,7.00,18.0
YearsSinceLastPromotion,1470.0,2.187755,3.222430,0.0,0.00,1.0,3.00,15.0
YearsWithCurrManager,1470.0,4.123129,3.568136,0.0,2.00,3.0,7.00,17.0

In [12]:
print("Attrition employee ID candidates:")
print(
    attrition_df[
        ["EmployeeNumber"]
    ].head(10)
)

Attrition employee ID candidates:
   EmployeeNumber
0               1
1               2
2               4
3               5
4               7
5               8
6              10
7              11
8              12
9              13

In [13]:
print(
    "Unique EmployeeNumber:",
    attrition_df["EmployeeNumber"].nunique()
)

print(
    "Total rows:",
    len(attrition_df)
)

Unique EmployeeNumber: 1470
Total rows: 1470

In [14]:
print("Attrition ID columns:")
print(
    [
        c for c in attrition_df.columns
        if "id" in c.lower() or "number" in c.lower()
    ]
)

print("\nEngagement ID columns:")
print(
    [
        c for c in engagement_df.columns
        if "id" in c.lower() or "number" in c.lower()
    ]
)

Attrition ID columns:
['EmployeeNumber']

Engagement ID columns:
['Employee ID']

In [15]:
attrition_roles = set(
    attrition_df["JobRole"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
    .unique()
)

occupation_titles = set(
    occupation_df["Title"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.lower()
    .unique()
)

role_matches = attrition_roles.intersection(
    occupation_titles
)

print("Attrition roles:", len(attrition_roles))
print("Occupation titles:", len(occupation_titles))
print("Exact normalized matches:", len(role_matches))

print("\nMatches:")
for role in sorted(role_matches):
    print(role)

Attrition roles: 9
Occupation titles: 1016
Exact normalized matches: 0

Matches:

In [16]:
profile = []

for name, df in datasets.items():

    profile.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "missing_cells": int(df.isnull().sum().sum()),
        "memory_mb": round(
            df.memory_usage(deep=True).sum() / 1024**2,
            2
        )
    })

profile_df = pd.DataFrame(profile)

display(profile_df)

            dataset   rows  columns  duplicate_rows  missing_cells  memory_mb
0         Attrition   1470       35               0              0       1.12
1        Engagement   2845       28               0              0       3.77
2        Occupation   1016        3               0              0       0.42
3  Essential Skills  18200       15               0           9100      11.90
4   Software Skills  31821        7               0              0      15.25

In [17]:
profile_df.to_csv(
    "../data/processed/dataset_profile.csv",
    index=False
)